
["Villager Settings"]
	#Enable Ramadan Delight villager trades (all)
	enableVillagerTrades = true
	#Enable Ramadan Delight farmer villager trades (such as parsley, dates...)
	enableFarmerVillagerTrades = true
	#Enable Ramadan Delight Mason villager trades (such as Mosaic Tiles)
	enableMasonVillagerTrades = true
	#Enable Ramadan Delight Wandering Trader trades
	enableWanderingTrades = true

